# Generated by Django 5.2.2 on 2026-02-02 12:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_bookinstance_language_book_language"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="language",
            name="language_name_case_insensitive_unique",
        ),
        migrations.AlterField(
            model_name="author",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="birth"),
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="language_name_casei_unique",
                violation_error_message="Language already exists (case insensitive match)",
            ),
        ),
    ]
